s

diff --git a/mygive-test b/mygive-test
--- a/mygive-test
+++ b/mygive-test
@@ -39,12 +39,14 @@ for d in $des_path;do
             stdin=$(cat $des_path/$f/stdin 2>/dev/null)  
             exit_status=$(cat $des_path/$f/exit_status 2>/dev/null) 
             stderr=$(cat $des_path/$f/stderr 2>/dev/null) 
+            stderr_1=$(mktemp)
+            cat $des_path/$f/stderr > "$stderr_1" 2>/dev/null
             file_stdout=$(mktemp)
             file_stderr=$(mktemp)
             desired_output=$(mktemp)
             # my standard output file
             stdout_tempfile=$(mktemp)
-            output_std=$(echo "$stdin" | "./$file" $arguments)
+            output_std=$(echo "$stdin" | "./$file" $arguments 2>/dev/null)
             echo "$stdin" | "./$file" $arguments >"$stdout_tempfile" 2>"$file_stderr"
             exit_status_real=$?
 
@@ -71,8 +73,7 @@ for d in $des_path;do
             echo "$stdout_option" >"$file_stdout" 
             echo "$stdout_standard" >"$desired_output"
             
-            stderr_1=$(mktemp)
-            echo $stderr > "$stderr_1"
+            
             x=$(wc -c < "$stdout_tempfile")
             y=$(wc -c < "$stdout_standard_tempfile")
             a=$(($x - $y))
@@ -88,8 +89,14 @@ for d in $des_path;do
                         echo "* Test $f failed."
                         fail=$((fail + 1))
                         echo "Missing newline at end of stdout"
+                    elif echo $options | grep -q 'd'; then
+                        echo "* Test $f passed."
+                        pass=$((pass + 1))
+                    elif echo $options | grep -q 'w';then
+                        echo "* Test $f passed."
+                        pass=$((pass + 1))
                     elif [ $a -eq 0 ];then
-                        content_std=$(echo "$stdin" | "./$file" $arguments)
+                        content_std=$(echo "$stdin" | "./$file" $arguments 2>/dev/null)
                         if [ "$stdout" != "$content_std" ];then
                             echo "* Test $f failed."
                             fail=$((fail + 1))
@@ -135,29 +142,58 @@ for d in $des_path;do
                     echo ""
                 fi
             else
-                if [ "$a" -ne 0 ];then 
+                if [ "$a" -eq 1 ] ;then 
+                    echo "* Test $f failed."
+                    fail=$((fail + 1))
+                    echo "Extra newline at end of stdout"
+                elif [ "$b" -eq 1 ]; then
+                    #VVVVV
+                    echo "* Test $f failed."
+                    fail=$((fail + 1))
+                    echo "Missing newline at end of stdout"
+                elif [ "$a" -ne 0 ];then
                     echo "* Test $f failed."
                     fail=$((fail + 1))
                     printf -- "--- Incorrect stdout of $(wc -c < "$stdout_tempfile") bytes:\n"
                     cat "$stdout_tempfile"
                     echo ""
-
                     printf -- "--- Correct stdout is these $(wc -c < "$stdout_standard_tempfile") bytes:\n"
                     cat "$stdout_standard_tempfile"
                     echo ""
                 else
-                    echo "* Test $f passed."
-                    pass=$((pass + 1))
+                    if [ ! -z "$stderr" ];then
+                        if ! cmp -s "$file_stderr" "$stderr_1"; then
+                            :
+                        else
+                            echo "* Test $f passed."
+                            pass=$((pass + 1))
+                        fi
+                    else
+                        echo "* Test $f passed."
+                        pass=$((pass + 1))
+                    fi
                 fi
             fi
             if ! cmp -s "$file_stderr" "$stderr_1"; then
                 if [ ! -z "$stderr" ];then
-                    printf -- "--- Incorrect stderr of $(wc -c < "$stdout_tempfile") bytes:\n"
-                    cat "$file_stderr"
-                    echo ""
-                    printf -- "--- Correct stderr is these $(wc -c < "$stdout_standard_tempfile") bytes:\n"
-                    cat "$stderr_1"
-                    echo ""
+                    content_std=$(echo "$stdin" | "./$file" $arguments 2>/dev/null)
+                    if [ "$stdout" = "$content_std" ];then
+                        echo "* Test $f failed."
+                        fail=$((fail + 1))
+                        printf -- "--- Incorrect stderr of $(wc -c < "$file_stderr") bytes:\n"
+                        cat "$file_stderr"
+                        echo ""
+                        printf -- "--- Correct stderr is these $(wc -c < "$stderr_1") bytes:\n"
+                        cat "$stderr_1"
+                        echo ""
+                    else
+                        printf -- "--- Incorrect stderr of $(wc -c < "$file_stderr") bytes:\n"
+                        cat "$file_stderr"
+                        echo ""
+                        printf -- "--- Correct stderr is these $(wc -c < "$stderr_1") bytes:\n"
+                        cat "$stderr_1"
+                        echo ""
+                    fi
                 fi
             fi
             
@@ -173,4 +209,6 @@ for d in $des_path;do
     done
 done
 echo "** $pass tests passed, $fail tests failed"
+rm -f "$file_stdout" "$file_stderr" "$stdout_tempfile" "$desired_output" "$stderr_1" "$stdout_standard_tempfile"
+
 
